#include "pico/cyw43_arch.h"
#include "pico/stdlib.h"
#include "lwip/apps/httpd.h"
#include "lwip/tcp.h"
#include "fsdata.h"       // Generated by tools/makefsdata.py
#include "wifi/WifiDriver.h"
#include <string.h>
#include <stdio.h>

static const fs_file_t* find_file(const char* uri) {
    // uri comes as "/index.html"
    const char* path = uri + 1; // skip leading '/'
    for (unsigned int i = 0; i < sizeof(fs_files)/sizeof(fs_file_t); i++) {
        if (strcmp(fs_files[i].name, path) == 0) {
            return &fs_files[i];
        }
    }
    return nullptr;
}

// Custom lwIP HTTP handler for static files
err_t http_server_serve_file(struct tcp_pcb *pcb, const char *uri) {
    const fs_file_t* file = find_file(uri);
    if (!file) return ERR_OK;

    tcp_write(pcb, file->content, file->length, TCP_WRITE_FLAG_COPY);
    return ERR_OK;
}

void wifi_init_ap() {
    if (cyw43_arch_init()) {
        printf("Wi-Fi init failed\n");
        return;
    }

    // Start Pico W in AP mode
    cyw43_arch_enable_ap_mode(
        "GP2040-Config",     // SSID
        "pokemon123",        // Password
        CYW43_AUTH_WPA2_AES_PSK
    );

    printf("Wi-Fi AP started, serving embedded web UI\n");

    // Initialize the lightweight HTTP server
    httpd_init();

    // TODO: Register custom URI handlers if needed for config API
}

void wifi_poll_loop() {
    cyw43_arch_poll();  // Must be called frequently in main loop on core 1
    sleep_ms(10);
}