import os
import sys
import mimetypes

output = sys.argv[2] if len(sys.argv) > 2 else "src/wifi/fsdata.c"
folder = sys.argv[1] if len(sys.argv) > 1 else "www"

files = []

def to_c_bytes(data: bytes) -> str:
    return ",".join(str(b) for b in data)

def sanitize_name(path: str) -> str:
    out = []
    for ch in path:
        if ch.isalnum():
            out.append(ch)
        else:
            out.append("_")
    return "".join(out)

def make_http_header(path: str, content_length: int) -> bytes:
    mime_type, _ = mimetypes.guess_type(path)
    if mime_type is None:
        mime_type = "application/octet-stream"

    header = (
        "HTTP/1.0 200 OK\r\n"
        f"Content-Type: {mime_type}\r\n"
        f"Content-Length: {content_length}\r\n"
        "Cache-Control: no-cache\r\n"
        "\r\n"
    )
    return header.encode("ascii")

for root, dirnames, filenames in os.walk(folder):
    dirnames.sort()
    filenames.sort()

    for filename in filenames:
        full_path = os.path.join(root, filename)
        rel_path = os.path.relpath(full_path, folder).replace("\\", "/")

        with open(full_path, "rb") as f:
            content = f.read()

        web_path = "/" + rel_path
        aliases = [web_path]
        if rel_path == "index.html":
            aliases.append("/")

        for alias in aliases:
            files.append((alias, content))

with open(output, "w", encoding="utf-8", newline="\n") as f:
    f.write('#include "lwip/apps/fs.h"\n')
    f.write('#include "lwip/def.h"\n\n')
    f.write("/* Auto-generated by tools/makefsdata.py */\n\n")

    prev_struct_name = "NULL"
    struct_names = []

    for idx, (path, content) in enumerate(files):
        safe = sanitize_name(path.strip("/")) or "root"
        name_var = f"data_name_{idx}_{safe}"
        data_var = f"data_file_{idx}_{safe}"
        struct_var = f"file_{idx}_{safe}"

        header = make_http_header(path, len(content))
        full_payload = header + content

        name_bytes = path.encode("utf-8") + b"\x00"

        f.write(f"static const unsigned char {name_var}[] = {{{to_c_bytes(name_bytes)}}};\n")
        f.write(f"static const unsigned char {data_var}[] = {{{to_c_bytes(full_payload)}}};\n")
        f.write(
            f"static const struct fsdata_file {struct_var} = {{\n"
            f"    {prev_struct_name},\n"
            f"    {name_var},\n"
            f"    {data_var},\n"
            f"    sizeof({data_var}),\n"
            f"    FS_FILE_FLAGS_HEADER_INCLUDED\n"
            f"}};\n\n"
        )

        prev_struct_name = f"&{struct_var}"
        struct_names.append(struct_var)

    if struct_names:
        f.write(f"#define FS_ROOT {prev_struct_name}\n")
        f.write(f"#define FS_NUMFILES {len(struct_names)}\n")
    else:
        f.write("#define FS_ROOT NULL\n")
        f.write("#define FS_NUMFILES 0\n")